<?php

function custom_site_alert_form_alter(&$form, &$form_state, $form_id) {
    
    if ($form_id == 'site_alert_admin')
    {
        $site_alert_content = variable_get('site_alert_content', array('value' => '', 'format' => NULL));

        $form['site_alert_content']['#required'] = FALSE;

        $form['site_alert_content']['#type'] = 'text_format';

        $form['site_alert_content']['#base_type'] = 'textarea';

        $form['site_alert_content']['#format'] = 'full_html';
        $form['site_alert_content']['#default_value'] = $site_alert_content['value'];
        
    return $form;
    
    }
}
 ?>